name: Build suite


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Prepare the AVR Rust build environment
      run:
        docker build . --file Dockerfile.ci --tag avr-rust/avr_window.ci:$GITHUB_RUN_NUMBER

    - name: Compile the crate
      run:
        docker run avr-rust/avr_window.ci:$GITHUB_RUN_NUMBER

